Feature: Customer API Management
  As a system administrator
  I want to manage customer accounts through the API
  So that I can create and manage customer data programmatically

  @api @customer @ECOM-165
  Scenario: Verify POST /customers creates user with email and password only
    Given I have valid customer data with email and password
    When I create a new customer via POST /customers
    Then the customer should be created successfully
    And the response should contain the customer email
    And the response should contain a customer ID

  @api @customer @ECOM-166
  Scenario: Verify GET /customers lists all users
    Given I have access to the customers API
    When I retrieve all customers via GET /customers
    Then the response should be successful
    And the response should contain a list of customers

  @api @customer @ECOM-167
  Scenario: Verify POST /customers fails if password not provided
    Given I have customer data with email but no password
    When I attempt to create a customer via POST /customers
    Then the request should fail with appropriate error
    And the response should indicate password is required

  @api @customer @ECOM-168
  Scenario: Verify create customer with only email and password has names as empty string
    Given I have valid customer data with email and password only
    When I create a new customer via POST /customers
    Then the customer should be created successfully
    And the response should contain empty string for first_name
    And the response should contain empty string for last_name

  @api @customer @ECOM-169
  Scenario: Verify username is autogenerated based on email
    Given I have valid customer data with email and password
    When I create a new customer via POST /customers
    Then the customer should be created successfully
    And the response should contain a username based on the email

  @api @customer @ECOM-170
  Scenario: Verify create customer fails if email exists
    Given I have a customer with an existing email
    When I attempt to create another customer with the same email
    Then the request should fail with appropriate error
    And the response should indicate email already exists

  @api @customer @ECOM-171
  Scenario: Verify status code 404 for non-existing customer
    Given I have access to the customers API
    When I attempt to retrieve a non-existing customer via GET /customers/{id}
    Then the response should return status code 404
    And the response should indicate customer not found

  @api @customer @ECOM-172
  Scenario: Verify get customer by id returns one customer
    Given I have a created customer with a known ID
    When I retrieve the customer via GET /customers/{id}
    Then the response should be successful
    And the response should contain exactly one customer
    And the customer ID should match the requested ID
